# Generated by Django 5.2.3 on 2025-07-14 09:14

import django.db.models.deletion
import storage.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('last_download_date', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('file', models.FileField(upload_to=storage.models.generate_file_path)),
                ('share_link', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
